Фрагменты. Карусель
RottenConst/rebrain-android pull request #11
Opened 2019-05-12 21:43 UTC by RottenConst

2019-05-13 07:02 UTC, r3tam requested changes

2019-05-13 07:02 UTC, r3tam commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/base/BaseFragment.kt
> +open class BaseFragment : Fragment() {
Док

2019-05-13 07:02 UTC, r3tam commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/base/BaseFragment.kt
> +        Timber.d("%s onAttach", javaClass.simpleName)
рефлексия достаточно медленный инструмент, лучше сделать абстрактный геттер getName, который возвращает необходимое имя экрана

2019-05-13 07:02 UTC, r3tam commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/carousel/CarouselFragment.kt
> +class CarouselFragment : BaseFragment() {
Док лучще перенести к классу, а не к константе

2019-05-13 07:02 UTC, r3tam commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/carousel/CarouselFragment.kt
> +        imageCarousel = view.findViewById(R.id.image_food)
через kotlin.synthetic не работает?

2019-05-13 07:02 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/carousel/adapter/CarouselPageAdapter.kt
> + * FragmentStatePagerAdapter - хранит в паняти только соседнии страцы, остальные пересоздает,
опечатка

2019-05-13 07:02 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/carousel/adapter/CarouselPageAdapter.kt
> + *                             поэтому может притормаживать(подходит для большого числа страниц)
Не очень понятный вывод: хранит меньше, но тормозит. А другой вроде память засоряет, но быстрый. 
Думаю тут связь с притормаживанием лучше написать: почему может притормаживать, и как этого избежать.

2019-05-13 07:02 UTC, artem-zaitsev commented on FoodApp/app/src/main/res/layout/activity_main.xml
> +    <android.support.v4.view.ViewPager
отделите строкой

2019-05-13 07:02 UTC, artem-zaitsev commented on FoodApp/app/src/main/res/layout/fragment_carousel.xml
> +    <ImageView
отделяйте элементы строками

2019-05-20 20:34 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/carousel/CarouselFragment.kt
> +        imageCarousel = view.findViewById(R.id.image_food)
мой косяк, не сразу понял как с kotlin.synthetic во фрагментах работать

2019-05-21 07:11 UTC, r3tam requested changes

2019-05-21 07:11 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/base/BaseFragment.kt
> +/**
оставляйте пустую строку после импортов

2019-05-21 07:11 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/carousel/CarouselFragment.kt
> +/**
пустая строка, чтобы не сливалось

2019-05-21 07:11 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/carousel/CarouselFragment.kt
> + * класс фрагмент для резации карусели с картинками
опечатка

2019-05-21 07:11 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/carousel/CarouselFragment.kt
> +    private var pageNumber = 0
неправильный порядок членов класса. Лучше выносить наверх свойства

2019-05-21 07:11 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/carousel/CarouselFragment.kt
> +            val arg = Bundle()
есть bundleOf() в Kotlin

2019-05-21 07:11 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/carousel/adapter/CarouselPageAdapter.kt
> + * FragmentStatePagerAdapter - хранит в паняти только соседнии страцы, остальные пересоздает,
не исправлено

2019-05-22 21:55 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/carousel/CarouselFragment.kt
> +            val arg = Bundle()
не знал, спасибо

2019-05-23 21:41 UTC, r3tam approved these changes
Сливайте

2019-05-24 05:12 UTC, merged