Bottom bar
RottenConst/rebrain-android pull request #13
Opened 2019-07-08 20:43 UTC by RottenConst

Что-то не дается мне тема с боттом-баром

2019-07-11 09:02 UTC, r3tam requested changes
В целом довольно круто.
Добавил комментарий для улучшения и еще поправочка: именование растровых картинок - img_ , векторных - ic_

2019-07-11 09:02 UTC, r3tam commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/view/BottomBar.kt
> +class BottomBar @JvmOverloads constructor(context: Context, attrs: AttributeSet? = null) :
Реализация довольно неплоха, но можно еще улучшить. 
Смущает метод getButton - можно сделать один листенер у боттом бара, в который будет приходить тип выбпранного таба.
Было бы классно сделать так, чтобы была возможность конфигурации снаружи.
Например,

1. Сделать некоторый enum , который будет описывать типы табов в приложении.
2. здесь сделать (TabType) -> Unit , который надо будет задавать извне. Как листенер.
3. В слушателе клика брать из LinearLayout с кнопками iindex кнопки в children контейнера и из enum брать сам тип по index( работайте с ordinal у типа).(Учите что типы должны быть по порядку табов),
4. И в итоге вызывать слушатель с типом таба
5. чтобы обработать повторный клик - сделайте слушатель этого события(иногда повторный клик обрабатывается отдельно). И обрабатыайте его так же как и обычный - только по умолчанию пустая ляибда.
6. Храните текущий выбранный тип в отдельном свойстве

2019-08-01 05:26 UTC, r3tam requested changes

2019-08-01 05:26 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/view/BottomBar.kt
> +        when (type.ordinal) {
А чем отличаются ветки внутри when?

2019-08-01 05:26 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/view/ButtonTabBar.kt
> +class ButtonTabBar @JvmOverloads constructor(
Если это просто кнопка, то лучше не использовать Bar в названии. Bar - это обычно несколько кнопок.

2019-08-01 05:26 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/view/ButtonTabBar.kt
> +    lateinit var type: TabType
А зачем это свойство?

2019-08-01 20:23 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/view/BottomBar.kt
> +        when (type.ordinal) {
да, поторопился, недосмотрел...
исправил

2019-08-01 20:24 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/view/ButtonTabBar.kt
> +class ButtonTabBar @JvmOverloads constructor(
понял, учту

2019-08-01 20:27 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/view/ButtonTabBar.kt
> +    lateinit var type: TabType
да и правда.
забыл про него.
исправил.

2019-08-03 11:40 UTC, r3tam approved these changes

2019-08-05 17:22 UTC, merged