Screen integration
RottenConst/rebrain-android pull request #14
Opened 2019-08-05 20:10 UTC by RottenConst

может конечно я не совсем правильно понял что именно требовалось в задании

2019-08-07 17:52 UTC, r3tam requested changes
Имелось ввижу переключение фрагментов чере detach/attach на активити. Это позволяет не уничтожать фрагмент полностью, а лишь разрушать иерархию его вью.

2019-08-22 18:51 UTC, RottenConst commented
Исправил

2019-08-25 19:21 UTC, r3tam requested changes

2019-08-25 19:21 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/tabs/favorite/FavoriteTabFragment.kt
> +        activity?.findViewById<ButtonTab>(R.id.favorite_button_tab)?.switchColorButton(true)
Есть же kotlin.synthetic. Можно обращаться к вью сразу по айди.

2019-08-25 19:21 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/view/BottomBar.kt
> +                    type.event.invoke(type)
Можно без явного вызова invoke. Просто type.event()

2019-08-25 19:21 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/view/BottomBar.kt
> +                    type.event.invoke(type)
И возможно передача type в аргументы излишняя.

2019-08-26 10:38 UTC, RottenConst commented
Подправил

2019-08-31 18:37 UTC, r3tam approved these changes

2019-09-01 09:40 UTC, merged