Toolbar
RottenConst/rebrain-android pull request #15
Opened 2019-09-10 06:18 UTC by RottenConst

add toolbar on main tab

2019-09-10 07:14 UTC, r3tam requested changes

2019-09-10 07:14 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/MainActivity.kt
> +        setSupportActionBar(findViewById(R.id.food_toolbar))
В Котлин есть замечательная вещь - kotlin.synthetic. Она позволяет обращаться к вью сразу по id, без вызова findViewById()&

2019-09-10 07:14 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/MainActivity.kt
> +        setSupportActionBar(findViewById(R.id.food_toolbar))
И лучше в данном случае делать этот вызов из фрагмента. Так как тулбар принадлежит именно ему.

2019-09-10 07:14 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/tabs/main/MainTabFragment.kt
> +    private fun initToolbar(){
Располагайте приватные методы после публичных и перегруженных. Иначе код превращается в неструктурированную кашу.

2019-09-10 07:14 UTC, artem-zaitsev commented on FoodApp/app/src/main/res/layout/fragment_main.xml
> +            android:id="@+id/view_pager"
Лучше добавлять в идентификатор немного семантики. например `fragment_main_view_pager`. Это поможет избежать проблем в реальном приложении с путаницей идентификаторов и непонятными багами.

2019-09-10 09:58 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/MainActivity.kt
> +        setSupportActionBar(findViewById(R.id.food_toolbar))
Исправил

2019-09-10 10:00 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/tabs/main/MainTabFragment.kt
> +    private fun initToolbar(){
Спасибо исправил, постараюсь учесть

2019-09-10 10:01 UTC, RottenConst commented on FoodApp/app/src/main/res/layout/fragment_main.xml
> +            android:id="@+id/view_pager"
Спасибо, учту

2019-09-16 07:11 UTC, r3tam approved these changes
Сливайте

2019-09-16 10:36 UTC, merged