add RecyclerView
RottenConst/rebrain-android pull request #17
Opened 2019-10-02 18:28 UTC by RottenConst

2019-10-03 08:24 UTC, r3tam requested changes

2019-10-03 08:24 UTC, r3tam commented on FoodApp/app/src/main/AndroidManifest.xml
> +            android:hardwareAccelerated="true"
лучше этот атрибут использовать в крайних случаях

2019-10-03 08:24 UTC, r3tam commented on FoodApp/app/src/main/AndroidManifest.xml
> +            android:hardwareAccelerated="true"
как и тот , что ниже

2019-10-03 08:24 UTC, r3tam commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/list_main/ListPriceAdapter.kt
> +class ListPriceAdapter(
документация к классу

2019-10-03 08:24 UTC, r3tam commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/list_main/ListPriceAdapter.kt
> +
лишний пропуск строки

2019-10-03 08:24 UTC, r3tam commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/list_main/ListPriceAdapter.kt
> +
пустая строка

2019-10-03 08:24 UTC, r3tam commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/list_main/ListPriceAdapter.kt
> +
и на 37ой

2019-10-03 08:24 UTC, r3tam commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/tabs/favorite/FavoriteTabFragment.kt
> +        retainInstance = true
Напишите причину использования именно retainInstance.

2019-10-03 08:24 UTC, r3tam commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/view/BottomBar.kt
> +        val buttons = arrayOfNulls<ButtonTab>(2)
"магическое число". Константы лучше выводить в константы и называть по смыслу.

2019-10-03 08:24 UTC, artem-zaitsev commented on FoodApp/app/src/main/res/layout/layout_list_item_product.xml
> +<?xml version="1.0" encoding="utf-8"?>
отформатируйте файл

2019-10-03 20:17 UTC, RottenConst commented on FoodApp/app/src/main/AndroidManifest.xml
> +            android:hardwareAccelerated="true"
Когда есть время на работе, я писал код на рабочем компе, при запуске приложения на телефоне выдавал исключение единственное решение какое помогло это добавление этих атрибутов.
сейчас пока редко когда появляется время пописать код на работе, и на наших компах на работе использовать андройд студию то еще "удовольствие".
Поэтому убрал - на домашнем компьютере все нормально и без них

2019-10-03 20:17 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/list_main/ListPriceAdapter.kt
> +class ListPriceAdapter(
Добавил

2019-10-03 20:18 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/list_main/ListPriceAdapter.kt
> +
Убрал

2019-10-03 20:19 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/tabs/favorite/FavoriteTabFragment.kt
> +        retainInstance = true
Пробовал решить проблему при повороте, фрагменты пере создавались и накладывались друг на друга и оставался только выбранный таб, но нашел нашел более адекватный выход с помощью метода replace, вместо attach и detach.
Убрал

2019-10-03 20:21 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/view/BottomBar.kt
> +        val buttons = arrayOfNulls<ButtonTab>(2)
Исправил

2019-10-03 20:21 UTC, RottenConst commented on FoodApp/app/src/main/res/layout/layout_list_item_product.xml
> +<?xml version="1.0" encoding="utf-8"?>
Сделал

2019-10-08 06:36 UTC, r3tam approved these changes
Сливайте

2019-10-09 20:36 UTC, merged