Upload Images
RottenConst/rebrain-android pull request #18
Opened 2019-10-09 20:43 UTC by RottenConst

2019-10-10 06:42 UTC, r3tam requested changes

2019-10-10 06:42 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/list_main/ListPriceAdapter.kt
> +                Glide.with(context)
Контекст лучше брать из вью в данном варианте. Глайд "под капотом" привязывается к такому контексту.

2019-10-10 06:42 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/list_main/ListPriceAdapter.kt
> +            if (context != null) {
context ?: return  - смотрелось бы лаконичнее

2019-10-10 18:13 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/list_main/ListPriceAdapter.kt
> +                Glide.with(context)
Исправил

2019-10-10 18:15 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/list_main/ListPriceAdapter.kt
> +            if (context != null) {
не подумал про элвис оператор, спасибо

2019-10-11 06:55 UTC, r3tam requested changes
Небольшая правка

2019-10-11 06:55 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/list_main/ListPriceAdapter.kt
> +        holder.bind(product, holder.itemView.context)
зачем? itemView и так доступно внутри холдера)

2019-10-11 19:17 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/list_main/ListPriceAdapter.kt
> +        holder.bind(product, holder.itemView.context)
оу, точно)
Исправил

2019-10-13 15:14 UTC, r3tam approved these changes
Ок, сливайте

2019-10-13 20:25 UTC, merged