Switch view (grid)
RottenConst/rebrain-android pull request #20
Opened 2019-10-28 20:58 UTC by RottenConst

2019-10-29 07:18 UTC, r3tam requested changes

2019-10-29 07:18 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/list_main/ListPriceAdapter.kt
> +    var modeHolderView: Boolean = true
булевы свойства лучше называть начиная с глаголов is, was, has... Как бы подчеркивая, что они отвечают на вопрос да/нет. Это улучшает читаемость кода.

2019-10-29 19:47 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/list_main/ListPriceAdapter.kt
> +    var modeHolderView: Boolean = true
Подправил

2019-10-31 08:41 UTC, r3tam requested changes

2019-10-31 08:41 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/tabs/main/MainTabFragment.kt
> +            adapter.notifyDataSetChanged()
думаю notify можно вынести из веток

2019-10-31 18:46 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/tabs/main/MainTabFragment.kt
> +            adapter.notifyDataSetChanged()
Исправил

2019-11-01 06:58 UTC, r3tam approved these changes

2019-11-29 15:28 UTC, merged