add carousel in to the list
RottenConst/rebrain-android pull request #21
Opened 2019-12-03 20:41 UTC by RottenConst

2019-12-05 09:07 UTC, r3tam requested changes

2019-12-05 09:07 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/carousel/CarouselFragment.kt
> +        Glide.with(view.context).load(Generator.images[pageNumber]).into(image_food)
Передавайте список картинок как аргументы к фаргменту. Так мы разворачиваем управление каруселью и вам не придется менять внутренности класса, чтобы изменить способ получения картинок для загрузки.

2019-12-05 09:07 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/list_main/ListPriceAdapter.kt
> +            when (isLinearListModeView) {
лучше выделить вычисление layout в локальную переменную и потом передать его инфлейтеру.

2019-12-05 09:07 UTC, artem-zaitsev commented on FoodApp/app/src/main/res/drawable/select_dot.xml
> +                android:thickness="5dp"
лучше использовать size, а не thickness. <size/> доступен внутри <shape/>

2019-12-06 09:59 UTC, r3tam requested changes

2019-12-06 09:59 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/list_main/ListPriceAdapter.kt
> +            when (isLinearListModeView) {
не, я немного не то имел ввиду.
Скорее : 
```
val layout = when  {
    viewType == 0 -> R.layout. ...
    isLinear ->
    else ->
}

CarouselHolder(LayoutInflater.from(parent.context), parent, layout)
```

2019-12-09 20:42 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/list_main/ListPriceAdapter.kt
> +            when (isLinearListModeView) {
совсем забыл что так можно, спасибо, исправил

2019-12-12 16:36 UTC, r3tam approved these changes

2019-12-12 19:36 UTC, merged