Lifecycle owner
RottenConst/rebrain-android pull request #24
Opened 2019-12-28 07:06 UTC by RottenConst

2019-12-29 09:34 UTC, r3tam requested changes

2019-12-29 09:34 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/util/Logger.kt
> +    fun getLog(owner: LifecycleOwner, event: Lifecycle.Event){
скорее  logEvent. Гет не подходит так как нет возвращаемся значения.

2019-12-29 09:34 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/util/Logger.kt
> +class Logger : LifecycleObserver{
документация

2019-12-29 21:37 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/util/Logger.kt
> +class Logger : LifecycleObserver{
добавил

2019-12-29 21:38 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/util/Logger.kt
> +    fun getLog(owner: LifecycleOwner, event: Lifecycle.Event){
Поправил

2019-12-30 08:53 UTC, r3tam approved these changes

2020-02-06 17:40 UTC, merged