ViewModel
RottenConst/rebrain-android pull request #25
Opened 2020-02-25 20:48 UTC by RottenConst

2020-02-26 07:30 UTC, r3tam requested changes

2020-02-26 07:30 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/carousel/CarouselFragment.kt
> +        private val images = mutableListOf<Int>()
Зачем хранить список в статике?

2020-02-26 21:48 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/carousel/CarouselFragment.kt
> +        private val images = mutableListOf<Int>()
При повороте мне выкидывал exception(java.lang.IndexOutOfBoundsException: Index: 0, Size: 0), элемент который нужно загрузить почему-то пустой, и пока я не понял почему и где моя ошибка, первое что придумал - запихнуть список в статик, что бы долго не зацикливаться и поработать над заданием.

2020-02-27 07:30 UTC, r3tam requested changes

2020-02-27 07:30 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/carousel/CarouselFragment.kt
> +    private val images = mutableListOf<Int>()
Кажется, что лучше передавать данные в конструктор(добавляет немного "DI"). А если опасаетесь за иммутабельность(не хотите передавать ссылку, что правильно), то при передаче можно просто вызвать List.toList() - лист просто скопируется в новый.

2020-02-27 21:20 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/carousel/CarouselFragment.kt
> +    private val images = mutableListOf<Int>()
На сколько я знаю не рекомендуется передавать данные в конструкторе фрагмента, а только в Bundle, т.к. фрагмент менеджер при пересоздании фрагмента всегда ищет пустой конструктор, а иначе выдает исключение. Если может только использовать вторичный конструктор? (хотя что-то не особо вижу смысл в нем, может ошибась)

2020-03-03 07:42 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/carousel/CarouselFragment.kt
> +    private val images = mutableListOf<Int>()
Да, скорее в бандл, +

2020-03-03 07:43 UTC, r3tam approved these changes

2020-03-03 20:23 UTC, merged