Выделение Model-слоя
RottenConst/rebrain-android pull request #26
Opened 2020-03-17 06:25 UTC by RottenConst

2020-03-17 08:06 UTC, r3tam requested changes

2020-03-17 08:06 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/repository/ProductRepository.kt
> +    fun getProductList(generator: Generator): List<Product>{
док к классу

2020-03-18 05:03 UTC, midery requested changes

2020-03-18 05:03 UTC, midery commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/domain/ProductListViewModel.kt
> +class ProductListViewModel(private val product: ProductRepository) : ViewModel() {
Лучше давать переменным более осмысленные имена: если это репозиторий, у него должно быть окончание Repository, или Repo.

2020-03-18 05:03 UTC, midery commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/repository/ProductRepository.kt
> +    fun getProductList(generator: Generator): List<Product>{
Нужен док к публичному методу класса

2020-03-18 09:55 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/domain/ProductListViewModel.kt
> +class ProductListViewModel(private val product: ProductRepository) : ViewModel() {
Исправил. Спасибо за совет

2020-03-18 09:55 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/repository/ProductRepository.kt
> +    fun getProductList(generator: Generator): List<Product>{
добавил

2020-03-18 12:33 UTC, midery approved these changes

2020-03-31 22:32 UTC, merged