LiveData
RottenConst/rebrain-android pull request #27
Opened 2020-03-31 22:52 UTC by RottenConst

2020-04-01 08:30 UTC, midery requested changes

2020-04-01 08:30 UTC, midery commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/domain/ProductListViewModel.kt
> +    fun getListProduct() : MutableLiveData<List<Product>> = productLiveData
Если view знает про то, что liveData мутабельная, он может ее изменить. А это нарушит ответственность вью) 
Давай лучше сделаем метод getListProduct() типа `LiveData<List<Product>>`

2020-04-01 08:30 UTC, midery commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/domain/ProductListViewModel.kt
> +    fun refreshListProduct() : MutableLiveData<List<Product>> {
Тут возвращать ничего в принципе не нужно, этот метод выполняет действие, а не получает результат

2020-04-01 08:30 UTC, midery commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/tabs/main/MainTabFragment.kt
> +import timber.log.Timber
Лишний импорт закрался)

2020-04-01 08:30 UTC, midery commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/domain/ProductListViewModel.kt
> +    fun getListProduct() : MutableLiveData<List<Product>> = productLiveData
Кстати, вполне можно делать это не методом, а свойством с геттером
вроде 
```
    private val mProductLiveData: MutableLiveData<List<Product>> = MutableLiveData()
    val productLiveData: LiveData<List<Product>> get() = mProductLiveData
```
Так код будет попроще читаться, без множества гет-методов как в java

2020-04-01 08:30 UTC, midery commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/tabs/main/MainTabFragment.kt
> +          addGeneratedProduct(it)
В методе addGeneratedProduct следует очищать список перед добавлением, а то при двойной загрузке данных, списки будут задваиваться.

2020-04-01 08:30 UTC, midery commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/tabs/main/MainTabFragment.kt
> +        adapter.products.clear()
лучше не вручную очищать адаптер, а вызывать у ViewModel метод, вроде clearData(), которая бы сеттила в mutableLiveData пустой список. 
Но вообще, кажется, что у тебя тут его даже очищать не нужно: swipe refresh ведь используется как лоадер над контентом, а поэтому не требует предварительной очистки. Так что clear здесь можно убрать.

2020-04-01 22:01 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/domain/ProductListViewModel.kt
> +    fun getListProduct() : MutableLiveData<List<Product>> = productLiveData
Даже как-то не подумал... Спасибо за подсказку

2020-04-01 22:02 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/domain/ProductListViewModel.kt
> +    fun refreshListProduct() : MutableLiveData<List<Product>> {
да, точно, на автомате написал

2020-04-01 22:02 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/tabs/main/MainTabFragment.kt
> +import timber.log.Timber
Почистил

2020-04-01 22:10 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/tabs/main/MainTabFragment.kt
> +          addGeneratedProduct(it)
Точно, спасибо.

2020-04-01 22:22 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/tabs/main/MainTabFragment.kt
> +        adapter.products.clear()
Спасибо за консультацию)
Не сразу дошло, как лучше очищать старые данные тут, поэтому и попробовал написать такой костыль, хотя это даже не костыль получается.

2020-04-02 07:37 UTC, midery approved these changes

2020-04-02 07:37 UTC, midery commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/tabs/main/MainTabFragment.kt
> +        adapter.notifyDataSetChanged()
И тут можно не вызывать notifyDataSetChanged, потому что по факту датасет поменяется только когда продукты будут загружены, в методе addGeneratedProduct.

2020-04-02 13:22 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/tabs/main/MainTabFragment.kt
> +        adapter.notifyDataSetChanged()
исправил

2020-04-11 19:19 UTC, merged