Выделение хранилища для режима отображения
RottenConst/rebrain-android pull request #28
Opened 2020-04-21 18:40 UTC by RottenConst

2020-04-22 09:52 UTC, midery commented
В задачке не хватает репозитория для этого хранилища, который бы инкапсулировал логику доступа к данным.

2020-04-22 10:00 UTC, midery requested changes

2020-04-22 10:00 UTC, midery commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/iteractor/ProductModeStorage.kt
> +    fun saveProductModeView(viewModeProduct: Boolean, context: Context?) {
Сейчас у нас интерфейс хранилища сильно привязан к системе: чтобы извлечь какое-то значение, мы должны передать контекст.
Лучше в таких случаях поступать иначе: передавать контекст в конструктор приватным полем, и использовать его только для инициализации. 
Таким образом, для доступа извне это хранилище будет максимально простым.

2020-04-22 10:00 UTC, midery commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/iteractor/ProductModeStorage.kt
> +    fun getProductModeView(context: Context?): Boolean? {
Когда мы сохраняем возможные типы переменных, лучше использовать не Boolean, а enum. Всегда может добавиться новый тип представления на ui (например, горизонтальная карусель), и твоя переменная уже не будет покрывать всех кейсов.

2020-04-22 10:00 UTC, midery commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/tabs/main/MainTabFragment.kt
> +        adapter.isLinearListModeView = productMode.getProductModeView(context)!!
Старайся избегать `!!`-кричащего оператора, он приводит к крешам во времени выполнения. 
Лучше используй elvis `?:` оператор, `?.let { } `-конструкции, итд.

2020-04-23 18:54 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/tabs/main/MainTabFragment.kt
> +        adapter.isLinearListModeView = productMode.getProductModeView(context)!!
понял, постараюсь исправится

2020-04-23 18:56 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/iteractor/ProductModeStorage.kt
> +    fun getProductModeView(context: Context?): Boolean? {
теперь до меня дошла суть задания, спасибо

2020-04-23 18:57 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/iteractor/ProductModeStorage.kt
> +    fun saveProductModeView(viewModeProduct: Boolean, context: Context?) {
Исправил, но не совсем уверен, что до конца правильно все сделал

2020-04-24 08:54 UTC, midery requested changes

2020-04-24 08:54 UTC, midery commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/iteractor/ProductModeStorage.kt
> +enum class ProductModeView(val layout: Int) {
Лучше не держать здесь ссылки на андроидовские вьюхи, а просто ограничиться значениями 0, 1 в качестве id. Будет ок) 

И еще, можно чтобы в хранилище не добавлять when, сделать у enum компаньон наподобие: 

```
companion object { 
  fun getById(id: Int) = values().find { it.id == id } ?: LINEAR_MODE_VIEW_PRODUCT
}
```

И в хранилище уже доставать через этот метод

2020-04-24 08:54 UTC, midery commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/list_main/ListPriceAdapter.kt
> +    internal var PriceModeView: ProductModeView = ProductModeView.LINEAR_MODE_VIEW_PRODUCT,
по-моему этой переменной необязательно быть internal, можно и private) И сделай ее с маленькой буквы

2020-04-24 08:54 UTC, midery commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/iteractor/ProductModeStorage.kt
> +class ProductModeStorage(context: Context?) {
Все отлично исправил, молодец)

2020-04-26 13:51 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/iteractor/ProductModeStorage.kt
> +enum class ProductModeView(val layout: Int) {
Исправил.
Про компаньон спасибо, не додумался что-то.

2020-04-26 14:03 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/list_main/ListPriceAdapter.kt
> +    internal var PriceModeView: ProductModeView = ProductModeView.LINEAR_MODE_VIEW_PRODUCT,
Иде'шка сама сама добавила после рефакторинга, недоглядел, спасибо.
Эти свойства в адаптере у меня были public, или есть смысл сделать их private и добавить им методы для их изменения?

2020-04-26 14:03 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/iteractor/ProductModeStorage.kt
> +class ProductModeStorage(context: Context?) {
спасибо)

2020-04-27 08:12 UTC, midery commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/main/list_main/ListPriceAdapter.kt
> +    internal var PriceModeView: ProductModeView = ProductModeView.LINEAR_MODE_VIEW_PRODUCT,
В Kotlin это необязательно, ведь в нем можно переопределять getter/setter свойствам.

2020-04-27 08:13 UTC, midery approved these changes

2020-04-27 10:47 UTC, merged