Инверсия управления
RottenConst/rebrain-android pull request #29
Opened 2020-04-28 18:27 UTC by RottenConst

add interface IStorageModeView

2020-04-29 15:26 UTC, midery requested changes

2020-04-29 15:26 UTC, midery commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/iteractor/IStorageModeView.kt
> +    val context: Context?
Мы как раз раньше это обсуждали) 
Контекст не использоваться в интерфейсе сущности, чтобы отвязать ее от платформы. Он будет только в реализации. 
И лучше просто использовать именование ProductModeStorage, нейминг IStorageModeView скорее в .NET используется

2020-04-29 15:26 UTC, midery commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/iteractor/ProductModeStorage.kt
> +open class ProductModeStorage(final override val context: Context?) : IStorageModeView<ProductModeView> {
По-моему, этот класс не должен быть open, а переменная final) 
val-переменная и так final по-умолчанию.

2020-04-29 15:26 UTC, midery commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/iteractor/IStorageModeView.kt
> +interface IStorageModeView<Type : Enum<Type>> {
И еще, в интерфейсе и методах хранилища явно указывается, что оно извлекает modeView, и поэтому типизация по ProductModeView кажется бессмысленной) 

Скорее, нужно сделать интерфейс Storage<T> с методами save(data: T) и get(): T, от него унаследовать интерфейс ProductModeStorage, а от него в свою очередь DefaultProductModeStorage, в которой будет реализация) 
Это будет самая корректная реализация

2020-04-29 15:26 UTC, midery commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/repository/ProductModeViewRepository.kt
> +class ProductModeViewRepository(context: Context?) : ProductModeStorage(context) {
Это неверная запись, абстрактный ProductModeStorage должен поставляться так же как и раньше в конструктор приватным полем. Сейчас у тебя репозиторий зависит от контекста, это значит, что он зависит от android framework. это не очень верно) 
Прочитай про принцип инверсии зависимостей, например, тут: https://habr.com/ru/post/313796/

2020-05-06 22:10 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/iteractor/IStorageModeView.kt
> +    val context: Context?
Да что-то я здесь совсем накосячил, пока экспериментировал

2020-05-06 22:10 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/iteractor/ProductModeStorage.kt
> +open class ProductModeStorage(final override val context: Context?) : IStorageModeView<ProductModeView> {
исправил

2020-05-06 22:11 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/iteractor/IStorageModeView.kt
> +interface IStorageModeView<Type : Enum<Type>> {
Исправил, если все правильно понял

2020-05-06 22:16 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/repository/ProductModeViewRepository.kt
> +class ProductModeViewRepository(context: Context?) : ProductModeStorage(context) {
Большое спасибо за ссылку)
Архитектура для меня сложная тема, маловато практики у меня, но по понемногу стараюсь разбираться

2020-05-07 10:34 UTC, midery requested changes
Можешь почитать в принципе про все принципы SOLID: 
https://medium.com/webbdev/solid-4ffc018077da
Они довольно важны для любого разработчика, не только в мобильной разработке. И чаще всего, хотя бы знания их определений требуют на собеседованиях во многие компании. 
Так же, будет большим плюсом изучить принципы Clean Architecture, например, по этой статье: https://habr.com/ru/company/mobileup/blog/335382/ . На переработках клина действует большинство серьезных компаний, и в больших проектах без этого подхода никуда.
И еще, могу посоветовать почитать хотя бы немного про паттерны проектирования, например, здесь: https://refactoring.guru/ru/design-patterns 
Тут очень подробно и понятно все расписано. 

Это все можешь не изучать сиюминутно, но я бы эти статейки сохранил, и вернулся к ним, например, когда будешь чувствовать недостаток знаний, или будешь думать о трудоустройстве.

2020-05-07 10:34 UTC, midery commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/iteractor/Storage.kt
> +interface Storage<Type : Enum<Type>> {
Да, все почти верно) 
Только не нужно наследовать тип от enum. 
Лучше просто сделай `interface Storage<T>` с методами save, get

2020-05-07 10:34 UTC, midery commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/repository/ProductModeViewRepository.kt
> +class ProductModeViewRepository(private val productModeStorage: StorageModeView) {
А здесь все верно, молодец)

2020-05-07 15:18 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/iteractor/Storage.kt
> +interface Storage<Type : Enum<Type>> {
Исправил

2020-05-07 15:18 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/repository/ProductModeViewRepository.kt
> +class ProductModeViewRepository(private val productModeStorage: StorageModeView) {
Спасибо, при много благодарен за ссылки) сохранил)

2020-05-08 10:37 UTC, midery approved these changes

2020-05-08 17:45 UTC, merged