Dagger. Scope
RottenConst/rebrain-android pull request #34
Opened 2020-06-15 21:09 UTC by RottenConst

2020-06-17 10:03 UTC, midery requested changes

2020-06-17 10:03 UTC, midery commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/base/App.kt
> +        screeComponent = DaggerScreenComponent.builder()
Все ок, но только screenComponent должен билдится не здесь, а в конкретном экране. 

Точнее, ты можешь сделать метод buildScreenComponent() в Application-классе, и он будет возвращать тип ScreenComponent. 
А вот вызывать этот метод уже следует на конкретном экране, там же, где ты вызываешь inject(this). 


Иначе сейчас у тебя будет один скрин компонент на все экраны и его присутствие будет бессмысленным (скоуп будет таким же как и в app). А идея скоупов все же именно в том, чтобы у каждого экрана был свой список зависимостей, и они не пересекались между собой)

2020-06-17 17:25 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/base/App.kt
> +        screeComponent = DaggerScreenComponent.builder()
Да, что-то я упустил этот момент, спасибо.
Поправил

2020-06-24 12:22 UTC, midery approved these changes

2020-06-25 19:32 UTC, merged