intro activity
RottenConst/rebrain-android pull request #4
Opened 2019-03-11 07:44 UTC by RottenConst

2019-03-11 18:56 UTC, r3tam requested changes

2019-03-11 18:56 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/intro/IntroActivity.kt
> +/**
лучше делать отступ после импортов

2019-03-11 18:56 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/splash/SplashActivity.kt
> +        val isFirst = applicationContext
лучше сделать утилитный класс для работы с SharedPreferences

2019-03-11 18:56 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/splash/SplashActivity.kt
> +            startActivity(Intent(applicationContext, IntroActivity::class.java))
сделайте компаньон с методом start у активити, который полностью отвечает за работу с интентом и тд

2019-03-11 18:56 UTC, artem-zaitsev commented on FoodApp/app/src/main/res/layout/activity_intro.xml
> +<android.support.constraint.ConstraintLayout
автоформатирование

2019-03-12 06:09 UTC, r3tam requested changes

2019-03-12 06:09 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/utils/PreferencesUtils.kt
> +  * Утилитные методы для работы с SharedPreferences
не совсем это имел ввиду. Скорее некоторый класс/объект, который является оберткой над SharedPrefs, предоставляет API для получения/установки значений по ключам. Такие классы полезны.так как в случае их использования Вы сможете подменить способ хранения данных не переписывая все каждый раз.

Эти методы можно оставить, но внутри должен использоваться вышеописанный класс

2019-03-12 06:09 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/utils/PreferencesUtils.kt
> +fun notFirstRunApp(context: Context) {
методы/функции должны начинаться с глагола(они являются неким действием)

2019-03-17 13:34 UTC, r3tam requested changes

2019-03-17 13:34 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/splash/SplashActivity.kt
> +        fun start(context: Context, activity: Activity) {
лучше сделать у каждой конкретной активити такой метод.
IntroActivity.start(this). 
Этот метод будет полностью отвечать за работу с параметрами и интентом для активити.

2019-03-17 13:34 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/utils/PreferencesUtils.kt
> +fun isFirstRunApp(context: Context): Boolean {
лучше сделать для этого отдельный класс-помощник, который отвечает за работу с прогрессом пользователя по всяким подсказкам. Это может быть не только интро, но и любые события, показывающиеся однократно.

2019-03-17 13:34 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/utils/PreferencesUtils.kt
> +fun runNotActivity(context: Context) {
не очень хорошее наименование

2019-03-19 16:29 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/screen/intro/IntroActivity.kt
> +/**
Не исправлено

2019-03-19 16:40 UTC, r3tam requested changes
Небольшие замечания по вспомогательным классам. Будут вопросы, пишите сразу в телеграмм.

2019-03-19 16:40 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/MainActivity.kt
>  class MainActivity : AppCompatActivity() {
Добавьте документацию к классу

2019-03-19 16:40 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/utils/HelpUserProgress.kt
> +    fun isNotRunNextTime(context: Context) {
Вообще не очень масштабируемое решение. Есть такая идея: сделать enum с этапами прогресса, например INTRO. Ordinal  у enum сохранять в shared Prefs. И уже по этому значению определять было показано интро или нет. Таким образом при появлении подобных экранов в будущем вы просто будете добавлять необходимые значения в enum.
Ну а у данного класса будет метод setProgress(Progress).
И геттеры например isIntroShown

2019-03-19 16:40 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/utils/HelpUserProgress.kt
> +    fun isNotRunNextTime(context: Context) {
И на будущее : методы, которые начинаются на is.. обычно возвращают Boolean и предназначены для проверок, а не установки свойств. Для установки лучше использовать set.. , или другие  глаголы, которые явно указывают на действие, которое произойдет.

2019-03-20 19:34 UTC, RottenConst commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/utils/HelpUserProgress.kt
> +    fun isNotRunNextTime(context: Context) {
Спасибо за подсказку

а про названия метода, я зациклился на том что эта подсказка вызывается 1 раз и ничего лучше в голову не лезло.... постараюсь так больше не делать

2019-03-21 06:20 UTC, r3tam requested changes

2019-03-21 06:20 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/utils/HelpUserProgress.kt
> +    fun isProgressHelpShow(context: Context, progress: ProgressHelp): Boolean =
needShowProgressHelp

2019-03-22 10:13 UTC, r3tam requested changes

2019-03-22 10:13 UTC, artem-zaitsev commented on FoodApp/app/src/main/kotlin/com/rebrain/konstload/foodapp/utils/HelpUserProgress.kt
> +    fun ShowProgressHelp(context: Context, progress: ProgressHelp): Boolean =
методы называются с маленькой буквы

2019-03-23 10:23 UTC, r3tam approved these changes

2019-03-23 11:37 UTC, merged